# MNIST database of handwritten digits
Dataset of 60,000 28x28 grayscale images of the 10 digits, along with a test set of 10,000 images.

### Import TensorFlow

In [24]:
import tensorflow as tf
print(tf.__version__)

2.16.1


### Set random seed

In [2]:
tf.random.set_seed(42)

### Import dataset
- This dataset can be imported
- High level API Keras has some datasets available
- You can look at all the datasets available here https://keras.io/datasets/
- mnist.load_data() returns two tuples (x_train, y_train), (x_test, y_test):
  - x_train, x_test: uint8 array of grayscale image data with shape (num_samples, 28, 28)
  - y_train, y_test: uint8 array of digit labels (integers in range 0-9) with shape (num_samples,).


In [3]:
(trainX, trainY), (testX, testY) = tf.keras.datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 5s 0us/step


In [4]:
trainX.shape,testX.shape

((60000, 28, 28), (10000, 28, 28))

In [5]:
trainX.reshape(-1,784).shape

(60000, 784)

In [6]:
trainX[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

### Print shape and some values of label

In [7]:
print(trainY.shape)
print('First 5 examples are: ', trainY[0:5])

(60000,)
First 5 examples are:  [5 0 4 1 9]


In [8]:
trainX.shape

(60000, 28, 28)

In [9]:
trainX[0].reshape(784).shape

(784,)

### One-hot encode the class vector
- convert class vectors (integers) to binary class matrix
- convert trainY and testY
- number of classes: 10
- we are doing this to use categorical_crossentropy as loss

In [10]:
tf.keras.utils.to_categorical(trainY, num_classes=10)[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [11]:
trainY = tf.keras.utils.to_categorical(trainY, num_classes=10)
testY = tf.keras.utils.to_categorical(testY, num_classes=10)

Print shape and some values

In [12]:
print(trainY.shape)
print('First 5 examples now are: ', trainY[0:2])

(60000, 10)
First 5 examples now are:  [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Build the model in Keras
- The Sequential model is a linear stack of layers.
- The model needs to know what input shape it should expect. For this reason, the first layer in a Sequential model (and only the first, because following layers can do automatic shape inference) needs to receive information about its input shape.
- You can also simply add layers via the .add() method
- You can read more about it here https://keras.io/getting-started/sequential-model-guide/
- Concepts of Batch Normalization will be covered in Upcoming sessions


In [13]:
# Initialize Sequential model
model = tf.keras.models.Sequential()

# Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(64, activation='relu'))
# Normalize the data
#model.add(tf.keras.layers.BatchNormalization())
# Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(10, activation='softmax'))
model.summary()

C:\Users\Sandeep\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\reshaping\reshape.py:39: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ reshape (Reshape)                    │ (None, 784)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │         100,480 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 109,386 (427.29 KB)

 Trainable params: 109,386 (427.29 KB)

 Non-trainable params: 0 (0.00 B)

### Compile the model
- Here we configure the model for training
- We will specify an optimizer, loss function and a metrics
- You can read more about it here https://keras.io/models/sequential/
- We will learn about optimizers and Loss functions in the sessions

In [14]:
# Comile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

### Fit the model
- .fit() trains the model for a fixed number of epochs (iterations on a dataset)
- An epoch is an iteration over the entire x and y data provided
- batch_size is the number of samples per gradient update such as batch of 32 , 64 etc, here we utilise complete batch ( 60000 samples )
- validation_data is the data on which to evaluate the loss and any model metrics at the end of each epoch

In [15]:
model.fit(trainX, trainY, validation_data=(testX, testY), epochs=15)

Epoch 1/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.7957 - loss: 5.5091 - val_accuracy: 0.9132 - val_loss: 0.3641
Epoch 2/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9201 - loss: 0.3174 - val_accuracy: 0.9429 - val_loss: 0.2276
Epoch 3/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9396 - loss: 0.2121 - val_accuracy: 0.9491 - val_loss: 0.1907
Epoch 4/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9524 - loss: 0.1662 - val_accuracy: 0.9520 - val_loss: 0.1875
Epoch 5/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9582 - loss: 0.1460 - val_accuracy: 0.9529 - val_loss: 0.1836
Epoch 6/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9616 - loss: 0.1388 - val_accuracy: 0.9545 - val_loss: 0.1999
Epoch 7/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9668 - loss: 0.1167 - val_accuracy: 0.9610 - val_loss: 0.1533
Epoch 8/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9699 - loss: 0.1036 - 

In [16]:
(trainX, trainY), (testX, testY) = tf.keras.datasets.mnist.load_data()

In [17]:
x_train = trainX.reshape(-1,784)
x_test = testX.reshape(-1,784)
x_train.shape,x_test.shape

((60000, 784), (10000, 784))

In [22]:
from sklearn.ensemble import RandomForestClassifier
# Import Random Forest Regressor

# Create a Random Forest Regressor
clf = RandomForestClassifier()

# Train the model using the training sets 
clf.fit(x_train, trainY)
# Model prediction on train data


RandomForestClassifier()

In [23]:
# Model Evaluation
from sklearn import metrics
print("Train Accuracy")
y_pred_train = clf.predict(x_train)
print('Accuracy:',metrics.accuracy_score(trainY, y_pred_train))
#print('F1score:',metrics.f1_score(trainY, y_pred_train))
      
print("Test Accuracy")
y_pred_test = clf.predict(x_test)
print('Accuracy:',metrics.accuracy_score(testY, y_pred_test))
#print('F1score:',metrics.f1_score(testY, y_pred_test))


Train Accuracy
Accuracy: 1.0
Test Accuracy
Accuracy: 0.9688
